### 1. ndarray

In [2]:
import numpy as np

In [3]:
arr = np.array(5)
print(arr)
print('the dimension of the array is: ', arr.ndim)
arr = np.array([1, 2, 3])
print(arr)
print('the dimension of the array is: ', arr.ndim)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("the dimension of the array is: ", arr.ndim)
arr = np.array([1, 'hello'])
print(arr)
arr = np.array([1, 3.5])
print(arr)

5
the dimension of the array is:  0
[1 2 3]
the dimension of the array is:  1
[[1 2 3]
 [4 5 6]]
the dimension of the array is:  2
['1' 'hello']
[1.  3.5]


### 2. the property of the ndarray

In [4]:
arr = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr)
print("the shape of the array is ", arr.shape)
print("the dimension of the array is ", arr.ndim)
print("the size of the array is ", arr.size)
print("the data type of the array is ", arr.dtype)
print("the transpose of the array is ", arr.T)

[[1 2 3 4 5]
 [2 3 4 5 6]]
the shape of the array is  (2, 5)
the dimension of the array is  2
the size of the array is  10
the data type of the array is  int64
the transpose of the array is  [[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]


### 3. the construction of the ndarray

In [13]:
list1 = [4, 5, 6]
arr = np.array(list1, dtype = np.float64)
print(arr.ndim)
print(arr)

# copy
arr1 = np.array(arr)
arr1[0] = 8
print(arr1)
print(arr)

# preallocation
arr = np.zeros((2, 4))
print(arr)
arr = np.zeros((200,), dtype = int)
print(arr)

# all ones
arr = np.ones((5, 8), dtype = int)
print(arr)

# non preallocated
arr = np.empty((4, 2))
print(arr)

arr = np.full((2, 4), 2025)
print(arr)

1
[4. 5. 6.]
[8. 5. 6.]
[4. 5. 6.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[2025 2025 2025 2025]
 [2025 2025 2025 2025]]


### 4. The construction of the ndarray

In [20]:
arr = np.arange(1, 10, 2)
print(arr)
arr = np.arange(2, 11, 2)
print(arr)

# linspace
arr = np.linspace(0, 10, 3)
print(arr)
arr = np.linspace(0, 100, 5)
print(arr)

# logspace
arr = np.logspace(0, 4, 2, base = 2)
print(arr)
arr = np.logspace(0, 4, 5, base = 10)
print(arr)

[1 3 5 7 9]
[ 2  4  6  8 10]
[ 0.  5. 10.]
[  0.  25.  50.  75. 100.]
[ 1. 16.]
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]


In [22]:
# special matrix
# Indentity matrix
arr = np.eye(3)
print(arr)

# diagonal matrix
arr = np.diag([1, 2, 3, 4])
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [29]:
# random array generation
arr = np.random.rand(2, 3)
print(arr)

# generate random numbers from a certain range
arr = np.random.uniform(3, 6, (2, 3))
print(arr)

# generate random int numbers from a certain range
arr = np.random.randint(3, 30, (2, 3))
print(arr)

# generate random numbers from a normal distribution
arr = np.random.randn(2, 3)
print(arr)

# set random seed 
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[0.2723164  0.71860593 0.78300361]
 [0.85032764 0.77524489 0.03666431]]
[[3.35008121 5.2538421  3.71765465]
 [3.76441804 5.57287659 5.84933708]]
[[28 17  3]
 [13 14  9]]
[[-1.6164342  -0.34456648 -0.38270796]
 [ 0.67826665  0.75069092 -1.78473676]]
[[4 5 7 8 3]
 [1 7 9 6 4]]


### 4. the data type of the ndarray

In [31]:
arr = np.array([1, 0, 1, 0], dtype = 'bool')
print(arr)
arr = np.array([1, 0, 2, 0], dtype = np.int8)
print(arr)

[ True False  True False]
[1 0 2 0]


### 5. index and slice


In [42]:
arr = np.random.randint(1, 100, 20)
print(arr)
print(arr[0], arr[19])
print(arr[:]) # get all the data
print(arr[2 : 3]) # start:end+1(include left but not include the right)
print(arr[slice(2, 5)])
print(arr[arr>10]) # bool selection

[12 19 53 65 56 65 37 49 96 59 40 38 55 93  6 27 16 92 56 11]
12 11
[12 19 53 65 56 65 37 49 96 59 40 38 55 93  6 27 16 92 56 11]
[53]
[53 65 56]
[12 19 53 65 56 65 37 49 96 59 40 38 55 93 27 16 92 56 11]


In [47]:
# index and slice of the 2D array
arr = np.random.randint(1, 100, (4, 8))
print(arr)
print(arr[1, 3])
print(arr[1, :])
print(arr[arr>50])

[[51 96  4 47 28 56 65 76]
 [22 80 31 81 16  8 68 80]
 [86 41 10 67 82 33 52 20]
 [93 40 77 56 73 79  6 49]]
81
[22 80 31 81 16  8 68 80]
[51 96 56 65 76 80 81 68 80 86 67 82 52 93 77 56 73 79]


### 6. the operations of the ndarray

In [61]:
# np.array add
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
# list add
c = [1, 2, 3]
d = [4, 5, 6]
print(c + d)
for i in range(len(c)):
    c[i] = (c[i] + d[i])
print(c)
print('\n')
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)
print(a + 3)

print("\n")
# broadcasting mechanism
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
print(a + b)

# matrix operations
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a @ b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1, 2, 3, 4, 5, 6]
[5, 7, 9]


[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


### 7.the common function of the numpy

In [75]:
# calculate the square root of the array
print(np.sqrt(9))
print(np.sqrt([1, 4, 9]))
arr = np.array([1, 25, 81])
print(np.sqrt(arr))
print(np.exp(1))
print(np.log(2.718281))
print(np.sin(np.pi/2))
print(np.cos(np.pi))
arr = np.array([-1, 1, 2, -3])
print(np.abs(arr))
# calculate a to the power of b
print(np.power(arr, 3))
# approximate the value
print(np.round([3.2, 4.5, 8.1, 9.6]))
print(np.ceil([3.2, 4.5, 8.1, 9.6]))
print(np.floor([3.2, 4.5, 8.1, 9.6]))
# examine the loss value NaN
np.isnan([1, 2, np.nan, 3])

3.0
[1. 2. 3.]
[1. 5. 9.]
2.718281828459045
0.999999695226903
1.0
-1.0
[1 1 2 3]
[ -1   1   8 -27]
[ 3.  4.  8. 10.]
[ 4.  5.  9. 10.]
[3. 4. 8. 9.]


array([False, False,  True, False])