# ChatGPT code ---AHP

In [ ]:
# ahp层次分析法
import numpy as np

A = np.array([
    [1,   1/3, 1/2, 1/3],
    [3,   1,   2,   1],
    [2,   1/2, 1,   1/2],
    [3,   1,   2,   1]
], dtype=float)

# 求特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(A)

# 找最大特征值
max_index = np.argmax(eigenvalues.real)

lambda_max = eigenvalues[max_index].real

# 最大特征值对应的特征向量
w = eigenvectors[:, max_index].real

# 归一化
w = w / w.sum()

print("最大特征值：", lambda_max)
print("权重：", w)

最大特征值： 4.010362902240901
权重： [0.1091138  0.35091289 0.18906042 0.35091289]


In [4]:
# 一致性检验
import numpy as np

def ahp_weight(A):
    """
    AHP:
    1. 计算最大特征值
    2. 获取对应特征向量
    3. 归一化得到权重
    """

    A = np.array(A, dtype=float)

    # 特征值、特征向量
    eigenvalues, eigenvectors = np.linalg.eig(A)

    # 最大特征值
    index = np.argmax(eigenvalues.real)

    lambda_max = eigenvalues[index].real

    # 最大特征值对应特征向量
    w = eigenvectors[:, index].real

    # 防止出现整体负号
    if np.all(w < 0):
        w = -w

    # 归一化
    w = w / w.sum()

    return lambda_max, w


def consistency_ratio(A):
    """
    计算 AHP 一致性比例 CR
    """

    A = np.array(A, dtype=float)

    n = A.shape[0]

    lambda_max, _ = ahp_weight(A)

    # 一致性指标 CI
    CI = (lambda_max - n) / (n - 1)

    # RI
    RI_table = {
        1: 0,
        2: 0,
        3: 0.58,
        4: 0.90,
        5: 1.12,
        6: 1.24,
        7: 1.32,
        8: 1.41,
        9: 1.45,
        10: 1.49
    }

    RI = RI_table[n]

    if RI == 0:
        return 0

    CR = CI / RI

    return CR


A = np.array([
    [1,   1/3, 1/2, 1/3],
    [3,   1,   2,   1],
    [2,   1/2, 1,   1/2],
    [3,   1,   2,   1]
])

lambda_max, weight = ahp_weight(A)

print("最大特征值：", lambda_max)
print("权重：", weight)

CR = consistency_ratio(A)

print("一致性比例 CR：", CR)

if CR < 0.1:
    print("一致性检验通过")
else:
    print("一致性检验不通过，需要调整判断矩阵")

最大特征值： 4.010362902240901
权重： [0.1091138  0.35091289 0.18906042 0.35091289]
一致性比例 CR： 0.0038381119410745576
一致性检验通过


In [5]:
import numpy as np


# =========================
# 1. AHP 权重计算
# =========================

def ahp_weight(A):

    A = np.array(A, dtype=float)

    # 求特征值和特征向量
    eigenvalues, eigenvectors = np.linalg.eig(A)

    # 最大特征值
    index = np.argmax(eigenvalues.real)

    lambda_max = eigenvalues[index].real

    # 对应特征向量
    w = eigenvectors[:, index].real

    # 防止整体为负
    if np.all(w < 0):
        w = -w

    # 归一化
    w = w / w.sum()

    return lambda_max, w


# =========================
# 2. 一致性检验
# =========================

def check_consistency(A):

    A = np.array(A, dtype=float)

    n = A.shape[0]

    lambda_max, _ = ahp_weight(A)

    CI = (lambda_max - n) / (n - 1)

    RI_table = {
        1: 0,
        2: 0,
        3: 0.58,
        4: 0.90,
        5: 1.12,
        6: 1.24,
        7: 1.32,
        8: 1.41,
        9: 1.45,
        10: 1.49
    }

    RI = RI_table[n]

    if RI == 0:
        CR = 0
    else:
        CR = CI / RI

    return lambda_max, CI, CR


# =========================
# 3. 准则层判断矩阵
# =========================

criterion_matrix = np.array([
    [1,   1/3, 1/2, 1/3],
    [3,   1,   2,   1],
    [2,   1/2, 1,   1/2],
    [3,   1,   2,   1]
])


criterion_lambda, criterion_weight = ahp_weight(
    criterion_matrix
)

criterion_lambda, CI, CR = check_consistency(
    criterion_matrix
)

print("===== 准则层 =====")

print("权重：")
print(criterion_weight)

print("最大特征值：", criterion_lambda)
print("CI：", CI)
print("CR：", CR)

if CR < 0.1:
    print("一致性通过")
else:
    print("一致性不通过")


# =========================
# 4. 各指标下的方案权重
# =========================

# 花费
cost = np.array([1.0, 0.8, 1.5])
cost_matrix = cost[:, None] / cost[None, :]

# 景色
scenery = np.array([1.2, 1.0, 1.5])
scenery_matrix = scenery[:, None] / scenery[None, :]

# 交通
transport = np.array([1.2, 1.5, 1.0])
transport_matrix = transport[:, None] / transport[None, :]

# 安全
safety = np.array([1.0, 0.9, 1.2])
safety_matrix = safety[:, None] / safety[None, :]


# 分别求权重
_, cost_weight = ahp_weight(cost_matrix)
_, scenery_weight = ahp_weight(scenery_matrix)
_, transport_weight = ahp_weight(transport_matrix)
_, safety_weight = ahp_weight(safety_matrix)


# =========================
# 5. 构造局部权重矩阵
# =========================

local_weight = np.column_stack([
    cost_weight,
    scenery_weight,
    transport_weight,
    safety_weight
])

print("\n===== 局部权重矩阵 =====")

print(local_weight)


# =========================
# 6. 综合评价
# =========================

final_score = local_weight @ criterion_weight

print("\n===== 最终结果 =====")

cities = ["北京", "上海", "成都"]

for city, score in zip(cities, final_score):
    print(city, ":", score)


# =========================
# 7. 排序
# =========================

ranking = np.argsort(final_score)[::-1]

print("\n===== 排名 =====")

for i in ranking:
    print(cities[i], final_score[i])

===== 准则层 =====
权重：
[0.1091138  0.35091289 0.18906042 0.35091289]
最大特征值： 4.010362902240901
CI： 0.003454300746967102
CR： 0.0038381119410745576
一致性通过

===== 局部权重矩阵 =====
[[0.3030303  0.32432432 0.32432432 0.32258065]
 [0.24242424 0.27027027 0.40540541 0.29032258]
 [0.45454545 0.40540541 0.27027027 0.38709677]]

===== 最终结果 =====
北京 : 0.32138897324239235
上海 : 0.2998172045027388
成都 : 0.3787938222548688

===== 排名 =====
成都 0.3787938222548688
北京 0.32138897324239235
上海 0.2998172045027388


# Gemini code ---AHP

In [1]:
import numpy as np

# 1. 构造判断矩阵 (假设有3个指标：性能、价格、便携)
# 第一行: 性能对性能(1), 性能对价格(5), 性能对便携(3)
# 第二行: 价格对性能(1/5), 价格对价格(1), 价格对便携(1/2)
# 第三行: 便携对性能(1/3), 便携对价格(2), 便携对便携(1)
A = np.array([
    [1,   5,   3],
    [1/5, 1,   1/2],
    [1/3, 2,   1]
])

print("--- 第一步：你的判断矩阵 ---")
print(A)

# 2. 求解特征值和特征向量 (这是AHP的数学核心)
# np.linalg.eig 会返回矩阵的所有特征值(eig_vals)和对应的特征向量(eig_vecs)
eig_vals, eig_vecs = np.linalg.eig(A)

# 找到最大的特征值 (提取实数部分，因为有时候会有复数)
max_eig_val = np.max(np.real(eig_vals))

# 找到最大特征值对应的特征向量
max_eig_index = np.argmax(np.real(eig_vals))
w_unnormalized = np.real(eig_vecs[:, max_eig_index])

# 3. 将特征向量归一化，变成我们需要的“权重” (总和为1)
weights = w_unnormalized / np.sum(w_unnormalized)

print("\n--- 第二步：计算得出的指标权重 ---")
print(f"性能权重: {weights[0]:.4f}")
print(f"价格权重: {weights[1]:.4f}")
print(f"便携权重: {weights[2]:.4f}")

# 4. 一致性检验 (防止胡乱打分)
n = A.shape[0] # 获取矩阵维度，这里 n=3
# 计算 CI (一致性指标)
CI = (max_eig_val - n) / (n - 1)

# 查表得到 RI (随机一致性指标)。如果是3个指标，RI固定为0.52 (不同教材可能微小差异，如0.58)
RI_dict = {1: 0, 2: 0, 3: 0.52, 4: 0.89, 5: 1.12, 6: 1.24, 7: 1.36}
RI = RI_dict[n]

# 计算 CR (一致性比率)
CR = CI / RI

print("\n--- 第三步：逻辑一致性检验 ---")
print(f"最大特征值: {max_eig_val:.4f}")
print(f"CR 值为: {CR:.4f}")

if CR < 0.1:
    print("结论：CR < 0.1，打分逻辑一致，权重有效通过！")
else:
    print("结论：CR >= 0.1，存在自相矛盾，请重新调整判断矩阵！")

--- 第一步：你的判断矩阵 ---
[[1.         5.         3.        ]
 [0.2        1.         0.5       ]
 [0.33333333 2.         1.        ]]

--- 第二步：计算得出的指标权重 ---
性能权重: 0.6483
价格权重: 0.1220
便携权重: 0.2297

--- 第三步：逻辑一致性检验 ---
最大特征值: 3.0037
CR 值为: 0.0036
结论：CR < 0.1，打分逻辑一致，权重有效通过！


In [2]:
import numpy as np

# 1. 数据准备: 4款手机 [价格(负向), 续航(正向), 拍照(正向)]
data = np.array([
    [4000, 10, 85], 
    [5000, 12, 90], 
    [3500, 8,  80], 
    [6000, 14, 95]
], dtype=float)
n, m = data.shape

# ================= 第一步：AHP 主观赋权 =================
# 构建 3x3 判断矩阵
A = np.array([
    [1,   3,   5],
    [1/3, 1,   2],
    [1/5, 1/2, 1]
])
# 计算特征值与特征向量
eig_vals, eig_vecs = np.linalg.eig(A)
max_eig_val = np.max(np.real(eig_vals))
w_ahp = np.real(eig_vecs[:, np.argmax(np.real(eig_vals))])
w_ahp = w_ahp / np.sum(w_ahp) # 归一化

# 一致性检验 (n=3时，RI=0.58)
CR = ((max_eig_val - 3) / 2) / 0.58
print(f"AHP 一致性比率 CR = {CR:.4f} (若<0.1则通过验证)")

# ================= 第二步：熵权法 客观赋权 =================
norm_data = np.zeros_like(data)
# 负向指标(价格)标准化
norm_data[:, 0] = (data[:, 0].max() - data[:, 0]) / (data[:, 0].max() - data[:, 0].min())
# 正向指标(续航, 拍照)标准化
for j in [1, 2]:
    norm_data[:, j] = (data[:, j] - data[:, j].min()) / (data[:, j].max() - data[:, j].min())

# 熵权法计算
p = (norm_data + 1e-5) / np.sum(norm_data + 1e-5, axis=0)
e = -1 / np.log(n) * np.sum(p * np.log(p), axis=0)
w_ewm = (1 - e) / np.sum(1 - e)

# ================= 第三步：计算组合权重 =================
w_comb = (w_ahp * w_ewm) / np.sum(w_ahp * w_ewm)
print(f"组合权重 [价格, 续航, 拍照] = {w_comb.round(4)}")

# ================= 第四步：TOPSIS 综合评价 =================
# 构建加权标准化矩阵 Z
Z = norm_data * w_comb

# 确定正负理想解 (Z_plus: 越大越好, Z_minus: 越小越好)
Z_plus = np.max(Z, axis=0)
Z_minus = np.min(Z, axis=0)

# 计算欧氏距离
D_plus = np.sqrt(np.sum((Z - Z_plus)**2, axis=1))
D_minus = np.sqrt(np.sum((Z - Z_minus)**2, axis=1))

# 计算贴近度 (最终得分，越接近1越好)
score = D_minus / (D_plus + D_minus)

print("\n最终排名得分 (A, B, C, D):")
for i, s in enumerate(score):
    print(f"手机 {chr(65+i)} 得分: {s:.4f}")

AHP 一致性比率 CR = 0.0032 (若<0.1则通过验证)
组合权重 [价格, 续航, 拍照] = [0.6326 0.2399 0.1275]

最终排名得分 (A, B, C, D):
手机 A 得分: 0.6994
手机 B 得分: 0.4437
手机 C 得分: 0.6995
手机 D 得分: 0.3005
